version: "3.7"

services:
  
  mongodb:
    image: mongo:4.2.3
    restart: always
    
    env_file: 
      - ./docker-env/mongodb.env

    volumes:
      - ./volumes/mongodb:/data/db

    ports:
      - "27017:27017"
